server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false

endpoints:
  shutdown:
    enabled: true
