server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    leaseRenewalIntervalInSeconds: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
        timeout:
          enabled: false

ribbon:
  maxAutoRetries: 3
  ReadTimeout: 30000
  ConnectTimeout: 3000
  OkToRetryOnAllOperations: true
  restclient:
    enabled: true

endpoints:
  routes:
    sensitive: true
    enabled: false
